### ISSUE TITLE
Test script with eyetracker in LLN

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/localizer_visual_motion#1]
See
https://github.com/marcobarilari/motion_Visual-Localizer/issues/10

**Comment by Remi-Gau** [comment]
- [ ] Refactor eyetracking script.
- [ ] Clean up should involve closing the eyeTracker

**Comment by marcobarilari** [comment]
open this in cpp-lln-lab/CPP_PTB and then close it
