### ISSUE TITLE
create automatic check to make sure that block length and IBI are multiples of the TR

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/localizer_visual_motion#27]
I think we should add an automatic check for this that send an error in case we don't the math wrong.

_Originally posted by @Remi-Gau in https://github.com/cpp-lln-lab/localizer_visual_motion/pull/25_

**Comment by marcobarilari** [comment]
related to #29

**Comment by marcobarilari** [comment]
agree, from my side this can be closed
