### ISSUE TITLE
eyetracker: record continuously?

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/localizer_visual_motion#49]
maybe we could switch to have a continuous recording of the eyetracker and not just have it "ON" during a block, no?

**Comment by marcobarilari** [comment]
sure it is definetly a valid alternative, though what is it the gain during the analysis?

I will open an issue in CPP_PTB  to add the feature to send 'messages' (tags) during the recording and then we can edit here in the main script

**Comment by marcobarilari** [comment]
- [ ] run the script in LLN to check for any problem (e.g. dealys)

- [ ] compare the output with and without continuos recording

**Comment by Remi-Gau** [comment]
@marcobarilari 
the associated PR has been merged but there are unticked boxes so we can't close that yet, right?

**Comment by marcobarilari** [comment]
now we can :)
