### ISSUE TITLE
Improve the doc (README)

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/localizer_visual_motion#82]
- [ ] installation
- [ ] general presentation
- [ ] experiment design

**Comment by marcobarilari** [comment]
@iqrashahzad14 hey, if you think that the `README` file with the repo explanations can be improved and have a suggestions on how we can centralize the ideas here ;)

**Comment by marcobarilari** [comment]
@Remi-Gau given the last merge of #83, can this be closed or we keep it open and updating the to do list?

**Comment by Remi-Gau** [comment]
yeah let's close this and open more specific issues: as you say "improving the doc" s always true.
