### ISSUE TITLE
[BUG]: Double check if tests for tasks make sense

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/localizer_visual_motion#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Tests checking for actual expected behavior

### Current Behavior

I am not sure the tests should expect what it is expecting

### Error message

No error message, the tests pass

### Environment

```markdown
CI github actions + moxunit
```

**Comment by Remi-Gau** [comment]
what tests are we exactly talking about? all of them?
